on:
  push:
  pull_request:
    branches: [master]
jobs:
  verify-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install development dependencies
        run: shards install
      - name: Run tests
        run: make lint spec
      - name: Make sure the files are formatted
        run: crystal tool format --check